[general]
import = ["alacritty_themes/themes/rose_pine.toml"]

[window]
decorations = "Buttonless"
startup_mode = "Fullscreen"
decorations_theme_variant = "light"
opacity = 1.0
blur = false

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
size = 16

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
